services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpass
      POSTGRES_DB: sonarqube
    volumes:
      - ~/sonarqube/postgres:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:latest
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonarpass
    ports:
      - "9000:9000"
    volumes:
      - ~/sonarqube/conf:/opt/sonarqube/conf
      - ~/sonarqube/extensions:/opt/sonarqube/extensions
      - ~/sonarqube/data:/opt/sonarqube/data
      - ~/sonarqube/logs:/opt/sonarqube/logs
