apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8080 # порт внутри кластера
      targetPort: 8000 # порт, на котором приложение слушает запросы внутри контейнера
      nodePort: 30080 # порт, на котором сервис доступен снаружи (можно выбрать в диапазоне 30000-32767)
  type: NodePort